### PR TITLE
backport from `dav1d` 1.2.0: picture: fix attaching props to delayed output pictures

### PR DESCRIPTION
**Pull request by fbossen**
Partially addresses #224

### CODE REVIEW

**Review by kkysen — APPROVED** [review]
LGTM but similarly to #517, I'll wait to merge until the other stack of PRs since there'll be some conflicts.

**Comment by rinon** [comment]
#513 was merged, can this go in now @kkysen?

**Comment by kkysen** [comment]
> #513 was merged, can this go in now @kkysen?

Oh, yes, I forgot about this one.  It conflicts with obu now, though, so I'll wait until I merge the obu PR, rebase this one, and then merge it.

**Comment by kkysen** [comment]
The rebased version, #599, was just merged, so closing this now.

**Pull request closed without merging**
