### PR TITLE
Enable full LTO

### PR DESCRIPTION
**Pull request by rinon**

### CODE REVIEW

**Review by kkysen — APPROVED** [review]
How much does this help perf?  Does it put us in the negative vs. C as @lqd saw, or was that mostly from `target-cpu=native`?

**Comment by lqd** [comment]
The overhead doesn’t change much. My results were mostly because of target-cpu + fat LTO + rebuilding std/alloc/core with them.

**Comment by rinon** [comment]
In my measurements this was a very small, if anything, speedup. I'll measure more carefully and post numbers.

**Comment by rinon** [comment]
This is a 0.2% speedup on my Ryzen 7700X. It's consistent and slightly above measurement noise, with only a small increase in build time. I'm going to put this in.

**Pull request merged**
