### PR TITLE
backport from `dav1d` 1.2.0: threading: Ensure passing the correct retval to decode_frame_exit

### PR DESCRIPTION
**Pull request by fbossen**
Partially address #224

### CODE REVIEW

**Review by kkysen — APPROVED** [review]
LGTM but I'm gonna hold off on merging as I think there'll be merge conflicts with #513.  Since this PR is way smaller, I'd prefer to rebase this one after #513 merges.

**Comment by fbossen** [comment]
@kkysen No problem. When do you expect #513 to be merged?

**Comment by kkysen** [comment]
> @kkysen No problem. When do you expect #513 to be merged?

Not sure, whenever @randomPoison or someone else has time to review #513 and the PRs before it.

**Comment by kkysen** [comment]
@fbossen, it's ready to merge now once it's rebased.

**Pull request merged**
