### PR TITLE
Fix alignment of lim_lut and refmvs_block (#115)

### PR DESCRIPTION
**Pull request by fbossen**

### CODE REVIEW

**Review by kkysen — COMMENTED** [review]
If it's the type that's being aligned everywhere we use it, we could just put a `#[repr(align(16))]` on the type and not need to update it everywhere.

**Review by thedataking — APPROVED** [review]
LGTM!

**Comment by fbossen** [comment]
> If it's the type that's being aligned everywhere we use it, we could just put a `#[repr(align(16))]` on the type and not need to update it everywhere.

A lot of duplicate changes are the result of `Dav1dFrameContext_lf` being defined in multiple files. If `Dav1dFrameContext_lf` were to be defined only once, then there wouldn't be a need to make multiple changes. For now, it may be better to have alignment directives closely match what is done in the original C code to make auditing (see #122) of such directives easier.

**Comment by randomPoison** [comment]
@fbossen Looks like there's a merge conflict on this now. Can you resolve that? I can merge this once you do.

**Comment by kkysen** [comment]
> A lot of duplicate changes are the result of `Dav1dFrameContext_lf` being defined in multiple files. If `Dav1dFrameContext_lf` were to be defined only once, then there wouldn't be a need to make multiple changes. For now, it may be better to have alignment directives closely match what is done in the original C code to make auditing (see #122) of such directives easier.

Ah, sorry, I didn't realize it's because the containing type wasn't deduplicated yet.  You're right then.

**Pull request merged**
