### PR TITLE
Fix `seek_stress` test papercut

### LINKED ISSUE #873: tests fail to link
I think a recent commit broke something that causes linker errors when running the tests for me. `git bisect` points to https://github.com/memorysafety/rav1d/commit/3bf213cde9c03fa8f13782445d1a1081cde8b176 as the cause. I'm on an x86_64 linux machine, and running the tests works fine before this commit.

```
folkertdev@folkertdev ~/r/r/build ((3bf213cd…)|BISECTING) [125]> cargo build --release && meson test \
                                                                   --suite testdata-8 \
                                                                   --suite testdata-10 \
                                                                   --suite testdata-12 \
                                                                   --suite testdata-multi
ninja: Entering directory `/home/folkertdev/rust/rav1d/build'
[2/3] Linking target tools/dav1d.
FAILED: tools/dav1d 
cc  -o tools/dav1d 'tools/f9d35d4@@dav1d@exe/dav1d.c.o' 'tools/f9d35d4@@dav1d@exe/dav1d_cli_parse.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,--start-group librav1d.a tools/libdav1d_input.a tools/libdav1d_output.a -pthread -lm -Wl,--end-group '-Wl,-rpath,$ORIGIN/..:$ORIGIN/' -Wl,-rpath-link,/home/folkertdev/rust/rav1d/build/ -Wl,-rpath-link,/home/folkertdev/rust/rav1d/build/tools
/usr/bin/ld: librav1d.a(std-eb8a07e9874efeeb.std.ee38bba0a237925c-cgu.0.rcgu.o): in function `std::sys::unix::weak::fetch':
/rustc/6b771f6b5a6c8b03b6322a9c77ac77cb346148f0/library/std/src/sys/unix/weak.rs:138: undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
[3/3] Linking target tests/seek_stress.
FAILED: tests/seek_stress 
cc  -o tests/seek_stress 'tests/59830eb@@seek_stress@exe/seek_stress.c.o' 'tools/f9d35d4@@dav1d@exe/dav1d_cli_parse.c.o' 'tools/f9d35d4@@dav1d_input@sta/input_input.c.o' 'tools/f9d35d4@@dav1d_input@sta/input_ivf.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,--start-group librav1d.a -pthread -lm -Wl,--end-group '-Wl,-rpath,$ORIGIN/..' -Wl,-rpath-link,/home/folkertdev/rust/rav1d/build/
/usr/bin/ld: librav1d.a(std-eb8a07e9874efeeb.std.ee38bba0a237925c-cgu.0.rcgu.o): in function `std::sys::unix::weak::fetch':
/rustc/6b771f6b5a6c8b03b6322a9c77ac77cb346148f0/library/std/src/sys/unix/weak.rs:138: undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Could not rebuild /home/folkertdev/rust/rav1d/build
```

tagging @thedataking

### PR DESCRIPTION
**Pull request by thedataking**
* Closes #873.

### CODE REVIEW

**Review by folkertdev — COMMENTED** [review]
nice! I verified that this works locally

with that, to close the issue, I think the readme should point to the `test.sh` script instead of a manual meson command. It's shorter, and should always mirror CI (e.g. if more test suites are added) 

just this could work

> Then you can run the tests with:
> 
> ```txt
> .github/workflows/test.sh -r target/release/dav1d
> ```

**Comment by thedataking** [comment]
> I think the readme should point to the `test.sh` script instead of [...]

Sure. I took a pass over the `README.md`, let me know what you think.

**Review by folkertdev — APPROVED** [review]

**Review by randomPoison — APPROVED** [review]
Ah thanks for fixing this, I'd been commenting out the seek_stress line in order to test locally.

**Review by kkysen — APPROVED** [review]
This is helpful, thanks!  I had been thinking we should say to use `test.sh` in the `README.md`, too.

**Pull request merged**
