### PR TITLE
`ipred.rs`: Replace C types with Rust equivalents

### LINKED ISSUE #815: Cleanup c2rust output in `ipred.rs`
* [ ] Cleanup helper functions to take safe arguments where possible (may take raw pointers as arguments currently).
* [ ] General cleanup of c2rust generated code in functions.
* [ ] Restore comments from original C.

The following functions still need to be cleaned up:

- [x] `splat_dc`
- [x] `cfl_pred`
- [x] `dc_gen_top`
- [x] `dc_gen_left`
- [x] `dc_gen`
- [x] `ipred_v_rust`
- [x] `ipred_h_rust`
- [x] `ipred_paeth_rust`
- [x] `ipred_smooth_rust`
- [x] `ipred_smooth_v_rust`
- [x] `ipred_smooth_h_rust`
- [x] `get_filter_strength`
- [x] `filter_edge`
- [x] `upsample_edge`
- [x] `ipred_z1_rust`
- [x] `ipred_z2_rust`
- [x] `ipred_z3_rust`
- [x] `filter_fn`
- [x] `ipred_filter_rust`
- [x] `cfl_ac_rust`
- [x] `pal_pred_rust`

### PR DESCRIPTION
**Pull request by randomPoison**
* Closes #815

### CODE REVIEW

**Review by kkysen — COMMENTED** [review]
I think we should stick to C types for FFI.  Uses inside functions we can change, though, and we can remove `ptrdiff_t` as you did.

**Comment by randomPoison** [comment]
Why should we stick to C types in FFI? I think it'd be better to use the concrete Rust types rather than `c_int` and friends.

**Comment by kkysen** [comment]
> Why should we stick to C types in FFI? I think it'd be better to use the concrete Rust types rather than `c_int` and friends.

Because it's `extern "C"`.  I think `c_int` is always `i32`, but others like `c_long` can be different, and I think it's better to be consistent with making the integer types in `extern "C" fn`s use C types.

**Comment by thedataking** [comment]
> Because it's extern "C". I think c_int is always i32, but others like c_long can be different, and I think it's better to be consistent with making the integer types in extern "C" fns use C types.

I agree. A key reason why 32-bit builds were broken after transpiling for a 64-bit host was that `c_ulong` is 

```
pub type c_ulong = u64;
```

for `x86_64-unknown-linux-gnu` but

```
pub type c_ulong = u32;
```

for `i686-unknown-linux-gnu`. I spent a lot of time getting that unbungled.

**Comment by randomPoison** [comment]
Ah okay noted. I'll close this for now then, I threw this together quickly because it was easy, going through and cleaning up C types within functions probably isn't worth the time right now.

**Pull request closed without merging**
