### PR TITLE
decode_b: Cleanup a chunk of code

### PR DESCRIPTION
**Pull request by randomPoison**
* Replace instances of hard coded value 8 with `DAV1D_MAX_SEGMENTS`.

### CODE REVIEW

**Review by kkysen — APPROVED** [review]
Did you already add `DAV1D_MAX_SEGMENTS` in a previous PR?  I forgot if you did

**Comment by randomPoison** [comment]
I thought I did, but apparently not? I checked though and it's not duplicated anywhere, so 🤷

**Comment by kkysen** [comment]
No, you did, in #145.

**Comment by randomPoison** [comment]
Oh huh. So this PR is a duplicate then 0: Thanks for catching that @kkysen!

**Comment by kkysen** [comment]
Wait, I don't think it's a duplicate.

**Pull request merged**
