### PR TITLE
`fn parse_frame_size`: Cleanup and make mostly safe

### PR DESCRIPTION
**Pull request by kkysen**
The only remaining `unsafe`ty is `rav1d_get_bit(s)`, which I'll do soon, and `Rav1dPicture::frame_hdr`, which will be `Arc`ed.

### CODE REVIEW

**Review by rinon — CHANGES_REQUESTED** [review]
This is too far removed from the original C code. Why?  All you needed here was to replace the pointer usage with references. Most of this PR is changes that reorganize the code, when it was already clean and effectively identical to the original C.

**Comment by kkysen** [comment]
> This is too far removed from the original C code. Why? All you needed here was to replace the pointer usage with references. Most of this PR is changes that reorganize the code, when it was already clean and effectively identical to the original C.

Which commits?  Do you mean 2e9c2e3, 2c5dc3e, or any of the others ones?  I didn't think they were that big changes, as most of the diff was just moving code/indentation around.

**Comment by rinon** [comment]
Most of the commits, but especially https://github.com/memorysafety/rav1d/commit/2e9c2e323d4e5e118be8db571a0859013be1ab85 and https://github.com/memorysafety/rav1d/commit/2c5dc3e9e645a837763bd7697691a0f6df4de0ce, here will make it harder to backport changes from upstream dav1d, and don't improve memory safety. We should be making the minimal edits necessary to get to safe Rust without diverging too much from upstream where we don't need to. Of course we want things to be readable, but we should not be trying to improve on the upstream C code readability or make things more idiomatic unless the original was unreadable.

>  I didn't think they were that big changes, as most of the diff was just moving code/indentation around.
Moving code/indentation are the biggest changes in terms of diffs and divergence from upstream. If it's necessary, that's one thing, but where it's not necessary we should try to avoid it.

**Comment by kkysen** [comment]
> Most of the commits, but especially 2e9c2e3 and 2c5dc3e, here will make it harder to backport changes from upstream dav1d, and don't improve memory safety. We should be making the minimal edits necessary to get to safe Rust without diverging too much from upstream where we don't need to. Of course we want things to be readable, but we should not be trying to improve on the upstream C code readability or make things more idiomatic unless the original was unreadable.

Did our general aims change?  I know we're focusing on more strictly memory safety now, but it's generally been a future goal to make things more idiomatic Rust and to keep things performant (usually the idiomatic way in Rust, e.x. iterators, is more performant).  Even with performance not the top top concern anymore (after safety), it's still quite important, so I've been converting things to iterators where that's simple (like here).  Also, for this part of the code specifically, I don't imagine there'd be many significant changes since the bitstream is frozen.

**Comment by Darkspirit** [comment]
https://www.memorysafety.org/initiative/av1/
> Milestones 1-4 of our [work plan](https://www.memorysafety.org/initiative/av1/av1-work-plan/) are funded.

> 4. Migrate block decoding
> [...]As soon as it is possible, we will change types to be safe and idiomatic.[...]

**Comment by kkysen** [comment]
I've removed the 2e9c2e3 and 2c5dc3e commits; the remaining ones are small and mostly around removing `&mut`s and stuff.

**Review by rinon — APPROVED** [review]

**Pull request merged**
