### PR TITLE
Backport x86 asm changes from dav1d 1.2.0

### PR DESCRIPTION
**Pull request by fbossen**
Partially addresses #225

### CODE REVIEW

**Review by kkysen — CHANGES_REQUESTED** [review]
We also need to re-transpile the C changes to Rust.  @thedataking, I assume you just did this recently for #215, so maybe you have some advice for doing it easily?  They're also simple enough to do manually (the larger `tests/checkasm/*` change doesn't need to be since we didn't transpile that in the first place), but we need to be careful doing it that way.

**Comment by fbossen** [comment]
I will do the port to Rust manually. As you say, the changes look simple enough

**Comment by fbossen** [comment]
Closing this PR. Will resubmit separate PRs as more C code actually needs to be pulled in.

**Comment by thedataking** [comment]
> I assume you just did this recently for https://github.com/memorysafety/rav1d/pull/215, so maybe you have some advice for doing it easily?

I simply re-transpiled the affected files using the `--filter` flag and made sure I only patched in the Rust lines corresponding to the changes in C files. Careful review will hopefully catch any inadvertent changes to the Rust.

**Pull request closed without merging**
